--- 
pid: tmp/pids/thin_ws.pid
log: log/thin_ws.log
max_conns: 1024
# environment: production
max_persistent_conns: 512
# servers: 1
# threaded: true
port: 3101
daemonize: true
# socket: tmp/sockets/thin.sock
